// Points scored by pressing buttons.
let curPoints = 0;
// Points to reach before passing the next level.
let maxPoints = 1;

// This array store all the variables/numbers of the buttons.
var values = [];
// This array store the information about if one particular button is pressed or not.
var toggle = [];


// This array remember the number generated by the function "generatePermutatedNumber()" and then help create a permutated number 
// and a more flexible generator of combinations.
let randGenerator = [];
// This variable store all the numbers the generator of combinations need to create the maximum score to achieve.
const maxNumberCombination = 2;
// If the game is over, the time stops and the player can't press anymore the buttons until they resets the game.
let gameOver = false;
// Store the previous maximum score and helps avoid repeating the same number in two or more levels.
let storeOldNumber;
// Used this for bug fixes. 
var i = 0;

//manage the updateText handle.
var textHandle;
//gets the timer text for editing it later.
//var counter = document.getElementById("timer");

// Reset some variable about the game
function resetLevelsTimer()
{
    levels = 0;
    seconds = maxSeconds;
    gameOver = false;
    curPoints = 0;
    time = 1000;
    document.getElementById("gameOverText").innerHTML = "Reach the exact amount of points for win!";
    document.getElementById("mainGame").classList.remove("fadeOut");
    document.getElementById("mainGame").classList.add("fadeIn");
    document.getElementById('mainGame').classList.remove("hide");
    document.getElementById('mainGame').classList.add("show");
    checkMaxPoints();
    document.getElementById("boxSize").classList.add("fadeOut");
    document.getElementById("boxSize").classList.remove("fadeIn");
    document.getElementById("boxSize").classList.add("hide");
    document.getElementById("boxSize").classList.remove("show");
}

//Every number of the buttons will be 1 and not pressed.
function resetValues()
{
    for(var i = 0; i < buttonClick.length; i++)
    {
        values[i] = 1;
        toggle[i] = false;
    }
}


//when a combination is good or bad, this function is called for setting the state of the buttons to "not pressed".
function resetButtonsScore()
{
    //reset the state of the buttons.
    for(var i = 0; i < toggle.length; i++)
    {
        toggle[i] = false;
    }
    //reset the score
    curPoints = 0;
    //generate a max score
    setMaxPoints();
   
}